services:
  - type: web
    name: dsa-guru-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dsa-guru-db
          property: connectionString
    plan: free

databases:
  - name: dsa-guru-db
    plan: free