# Generated by Django 6.0.5 on 2026-05-31 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('array', 'Array'), ('linked_list', 'Linked List'), ('stack', 'Stack'), ('queue', 'Queue'), ('tree', 'Tree'), ('graph', 'Graph'), ('hash_table', 'Hash Table'), ('sorting', 'Sorting')], max_length=50)),
                ('operation', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'topic', 'operation')},
            },
        ),
    ]
